# Generated by Django 4.1 on 2022-08-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
    ]
