# Generated by Django 4.1 on 2022-08-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productmodel_avg_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='avg_rating',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='avg_rating',
            field=models.ManyToManyField(blank=True, null=True, to='products.review'),
        ),
    ]
