# Generated by Django 4.1 on 2022-08-22 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productmodel_avg_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='avg_rating',
        ),
    ]
